//! SEND CUE SHEET (`5Dh`) construction.
//!
//! The cue sheet is how the drive is told what disc to make. Per ANSI
//! X3.304-1997 §6.2.11.2 it defines two things that matter here:
//!
//! 1. *"Generation of Sub-channel P and Q channel"* — the drive builds the TOC
//!    itself from these entries, which is why the CD-TEXT encoder leaves the
//!    P and Q bits clear.
//! 2. *"Format and block size of the data transferred by the WRITE command"* —
//!    per region, via each entry's DATA FORM byte.
//!
//! Everything in this module is pure and is tested against the sample cue
//! sheet the specification itself prints (Table 155).

/// Bytes in one cue sheet entry.
pub const ENTRY_BYTES: usize = 8;

/// Sectors in a two-second pause: the mandatory pregap before track 1, and the
/// pause before each later track on a disc that is not gapless.
pub const PREGAP_SECTORS: u32 = 150;

/// Lead-out is always announced as this track number.
pub const LEAD_OUT_TRACK: u8 = 0xAA;

// ── CTL/ADR (Tables 157-159) ────────────────────────────────────────────────
//
// The byte is CONTROL in the upper four bits, ADR in the lower four.
// CONTROL for audio: bit 7 = 4-channel, bit 6 = data track,
// bit 5 = digital copy permitted, bit 4 = pre-emphasis.

/// ADR = 1: the entry gives a start time for a TNO/INDEX.
const ADR_POSITION: u8 = 0x01;

/// ADR = 2: the entry carries the Media Catalog Number.
const ADR_CATALOG: u8 = 0x02;

/// ADR = 3: the entry carries a track's ISRC.
const ADR_ISRC: u8 = 0x03;

/// Digits in a Media Catalog Number (UPC/EAN).
pub const CATALOG_DIGITS: usize = 13;

/// Characters in an ISRC.
pub const ISRC_CHARS: usize = 12;

/// The CONTROL nibble for two audio channels, no pre-emphasis, digital copy
/// prohibited — shared by every entry kind, which differ only in their ADR.
const CTL_ADR_AUDIO_BASE: u8 = 0x00;

/// Two audio channels, no pre-emphasis, digital copy prohibited.
pub const CTL_ADR_AUDIO: u8 = CTL_ADR_AUDIO_BASE | ADR_POSITION;

/// As above, with the digital-copy-permitted bit set.
pub const CTL_ADR_AUDIO_COPY_PERMITTED: u8 = 0x20 | ADR_POSITION;

// ── DATA FORM (Tables 160 & 163) ────────────────────────────────────────────
//
// Bits 7-6 select the sub-channel form, bits 3-0 the main-data form:
//   sub  00 = drive generates zero subcode, 0 bytes transferred
//        01 = RAW, the host sends 96 bytes
//        11 = PACK, host sends packs and the drive adds ECC + interleaving
//   main  0 = the host sends 2352 bytes
//         1 = the drive generates the frame, 0 bytes transferred

const SUB_NONE: u8 = 0b00 << 6;
const SUB_RAW: u8 = 0b01 << 6;
const MAIN_HOST: u8 = 0x0;
const MAIN_DRIVE: u8 = 0x1;

/// Ordinary audio: 2352 bytes from us, subcode generated by the drive.
pub const DATA_FORM_AUDIO: u8 = SUB_NONE | MAIN_HOST;

/// Entirely drive-generated — used for the pregap and, without CD-TEXT, the
/// lead-in and lead-out. Zero bytes are transferred, but the sectors are still
/// written (§6.2.11.2.12 note 2).
pub const DATA_FORM_GENERATED: u8 = SUB_NONE | MAIN_DRIVE;

/// The CD-TEXT lead-in: `41h` — the drive generates the main channel while we
/// supply 96 bytes of raw P-W subchannel per sector.
///
/// RAW, not PACK. PACK is for CD+G in the *program area*, where the drive adds
/// ECC per pack; the CD-TEXT lead-in is written raw, with the 18-byte packs
/// laid end to end and spread six bits to a byte across the R-W channels.
pub const DATA_FORM_LEADIN_CD_TEXT: u8 = SUB_RAW | MAIN_DRIVE;

/// Minutes/seconds/frames, the address form the cue sheet speaks.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Msf {
    pub minute: u8,
    pub second: u8,
    pub frame: u8,
}

impl Msf {
    /// Absolute time for `sector`, where sector 0 is the start of the pregap.
    ///
    /// Absolute time counts from the start of the lead-in, so a track's
    /// absolute address is its LBA plus the 150-sector pregap.
    pub fn from_sector(sector: u32) -> Self {
        Self {
            minute: (sector / (60 * 75)) as u8,
            second: ((sector / 75) % 60) as u8,
            frame: (sector % 75) as u8,
        }
    }

    pub fn to_sector(self) -> u32 {
        (u32::from(self.minute) * 60 + u32::from(self.second)) * 75 + u32::from(self.frame)
    }
}

/// One 8-byte cue sheet line.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CueEntry {
    pub ctl_adr: u8,
    pub track: u8,
    pub index: u8,
    pub data_form: u8,
    pub scms: u8,
    pub address: Msf,
}

impl CueEntry {
    pub fn to_bytes(self) -> [u8; ENTRY_BYTES] {
        [
            self.ctl_adr,
            self.track,
            self.index,
            self.data_form,
            self.scms,
            self.address.minute,
            self.address.second,
            self.address.frame,
        ]
    }
}

/// One audio track's placement on the disc.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CueTrack {
    /// Length in sectors.
    pub sectors: u32,
    /// ISRC to record in the subchannel, when the library knows one.
    pub isrc: Option<String>,
}

impl CueTrack {
    pub fn new(sectors: u32) -> Self {
        Self { sectors, isrc: None }
    }
}

/// Split a fixed-width code into its cue sheet entries.
///
/// Both the catalog number and the ISRC are carried as pairs of entries whose
/// payload bytes hold the characters in order. A code of the wrong length is
/// dropped rather than truncated: half an ISRC on a disc is worse than none.
fn code_entries(code: &str, expected: usize) -> Option<Vec<u8>> {
    let bytes: Vec<u8> = code.trim().bytes().collect();
    (bytes.len() == expected && bytes.iter().all(u8::is_ascii_alphanumeric)).then_some(bytes)
}

/// Build a Session-At-Once cue sheet for an audio disc.
///
/// `cd_text` selects the lead-in form: with it, the lead-in expects 96 bytes of
/// raw P-W per sector from us; without it, the drive generates the lead-in
/// entirely.
///
/// `gapless` decides only what happens *between* tracks. Track 1's 150-sector
/// pregap is mandatory and is written either way; when `gapless` is false every
/// later track gets a 150-sector pause of its own, as its index 0 — the two
/// seconds a player counts down into the track. That is the rule macOS applies
/// through `kDRPreGapLengthKey`, so the toggle makes one disc rather than a
/// different one per platform.
///
/// Those pauses are drive-generated (`DATA_FORM_GENERATED`), exactly as track
/// 1's already is, because nothing here has audio to put in them: no bytes are
/// transferred for a pause, so the caller's `WRITE(10)` stream is the same
/// length gapped or gapless and only its addresses step over each pause. The
/// disc, however, does grow — every address from a pause onwards, the lead-out
/// included, moves by 150 sectors per gap.
///
/// Layout, in absolute time from the start of the lead-in:
/// lead-in, the 150-sector pregap as track 1 index 0, each track at index 1 —
/// preceded by its own index 0 when the disc is gapped — then the lead-out at
/// track `AAh`.
pub fn build_cue_sheet(
    tracks: &[CueTrack],
    cd_text: Option<Msf>,
    catalog: Option<&str>,
    gapless: bool,
) -> Vec<u8> {
    let mut raw: Vec<[u8; ENTRY_BYTES]> = Vec::with_capacity(tracks.len() * 4 + 5);

    // The catalog number comes first: the specification requires it "at the
    // beginning of the Cue sheet". Seven characters in the first entry, six in
    // the second, with the last byte spare.
    if let Some(digits) = catalog.and_then(|c| code_entries(c, CATALOG_DIGITS)) {
        let mut first = [0_u8; ENTRY_BYTES];
        let mut second = [0_u8; ENTRY_BYTES];
        first[0] = CTL_ADR_AUDIO_BASE | ADR_CATALOG;
        second[0] = CTL_ADR_AUDIO_BASE | ADR_CATALOG;
        first[1..8].copy_from_slice(&digits[..7]);
        second[1..7].copy_from_slice(&digits[7..13]);
        raw.push(first);
        raw.push(second);
    }

    let mut entries: Vec<CueEntry> = Vec::with_capacity(tracks.len() * 2 + 3);

    // Lead-in. Its control mode is that of the first track.
    //
    // With CD-TEXT the address is the disc's *real* lead-in start, read from
    // READ DISC INFORMATION — the drive uses it to know where the lead-in
    // begins. Without CD-TEXT the drive generates the whole lead-in and the
    // address is zero.
    entries.push(CueEntry {
        ctl_adr: CTL_ADR_AUDIO,
        track: 0x00,
        index: 0x00,
        data_form: if cd_text.is_some() {
            DATA_FORM_LEADIN_CD_TEXT
        } else {
            DATA_FORM_GENERATED
        },
        scms: 0x00,
        address: cd_text.unwrap_or(Msf::from_sector(0)),
    });

    // Track 1 index 0 — the two-second pause. The drive generates the silence,
    // so no audio is transferred for it.
    entries.push(CueEntry {
        ctl_adr: CTL_ADR_AUDIO,
        track: 0x01,
        index: 0x00,
        data_form: DATA_FORM_GENERATED,
        scms: 0x00,
        address: Msf::from_sector(0),
    });

    let mut cursor = PREGAP_SECTORS;
    for (position, track) in tracks.iter().enumerate() {
        // The pause before a track on a gapped disc. Track 1 is skipped
        // because the entry above already gave it the mandatory pregap, which
        // gapless never removes either. The drive generates the silence, as it
        // does for that first pregap, so the pause costs disc addresses and no
        // transfer.
        if position > 0 && !gapless {
            entries.push(CueEntry {
                ctl_adr: CTL_ADR_AUDIO,
                track: (position + 1) as u8,
                index: 0x00,
                data_form: DATA_FORM_GENERATED,
                scms: 0x00,
                address: Msf::from_sector(cursor),
            });
            cursor += PREGAP_SECTORS;
        }

        entries.push(CueEntry {
            ctl_adr: CTL_ADR_AUDIO,
            track: (position + 1) as u8,
            index: 0x01,
            data_form: DATA_FORM_AUDIO,
            scms: 0x00,
            address: Msf::from_sector(cursor),
        });
        cursor += track.sectors;
    }

    // Lead-out. Always index 01h (note 3), and its start is the last entry.
    entries.push(CueEntry {
        ctl_adr: CTL_ADR_AUDIO,
        track: LEAD_OUT_TRACK,
        index: 0x01,
        data_form: DATA_FORM_GENERATED,
        scms: 0x00,
        address: Msf::from_sector(cursor),
    });

    // Flatten, dropping each track's ISRC in immediately before it — the
    // specification requires ISRC "immediately preceding each Track's
    // information in the Cue Sheet". Index 1 is what it goes in front of, so on
    // a gapped disc the pair sits between a track's pause and its audio, which
    // is exactly where track 1's has always sat behind the mandatory pregap.
    for entry in &entries {
        if entry.index == 0x01 && entry.track != LEAD_OUT_TRACK {
            if let Some(track) = tracks.get((entry.track as usize).saturating_sub(1)) {
                if let Some(chars) =
                    track.isrc.as_deref().and_then(|c| code_entries(c, ISRC_CHARS))
                {
                    let mut first = [0_u8; ENTRY_BYTES];
                    let mut second = [0_u8; ENTRY_BYTES];
                    first[0] = CTL_ADR_AUDIO_BASE | ADR_ISRC;
                    second[0] = CTL_ADR_AUDIO_BASE | ADR_ISRC;
                    first[1] = entry.track;
                    second[1] = entry.track;
                    first[2..8].copy_from_slice(&chars[..6]);
                    second[2..8].copy_from_slice(&chars[6..12]);
                    raw.push(first);
                    raw.push(second);
                }
            }
        }
        raw.push(entry.to_bytes());
    }

    raw.into_iter().flatten().collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(sheet: &[u8]) -> Vec<CueEntry> {
        sheet
            .as_chunks::<ENTRY_BYTES>()
            .0
            .iter()
            .map(|c| CueEntry {
                ctl_adr: c[0],
                track: c[1],
                index: c[2],
                data_form: c[3],
                scms: c[4],
                address: Msf { minute: c[5], second: c[6], frame: c[7] },
            })
            .collect()
    }

    #[test]
    fn msf_round_trips_and_matches_the_red_book_clock() {
        assert_eq!(Msf::from_sector(0), Msf { minute: 0, second: 0, frame: 0 });
        // The 150-sector pregap is exactly two seconds — the sample cue sheet
        // in the specification shows track 1 index 1 at 00:02:00.
        assert_eq!(Msf::from_sector(150), Msf { minute: 0, second: 2, frame: 0 });
        assert_eq!(Msf::from_sector(74), Msf { minute: 0, second: 0, frame: 74 });
        assert_eq!(Msf::from_sector(75 * 60), Msf { minute: 1, second: 0, frame: 0 });
        for sector in [0, 1, 74, 150, 12_345, 359_849] {
            assert_eq!(Msf::from_sector(sector).to_sector(), sector);
        }
    }

    #[test]
    fn the_data_form_nibbles_decode_as_the_spec_defines_them() {
        // Table 163: bits 7-6 sub-channel form, bits 3-0 main-data form.
        assert_eq!(DATA_FORM_AUDIO, 0x00, "2352 from host, subcode from drive");
        assert_eq!(DATA_FORM_GENERATED, 0x01, "drive generates the whole frame");
        assert_eq!(DATA_FORM_LEADIN_CD_TEXT, 0x41, "raw P-W from host, main from drive");
    }

    #[test]
    fn ctl_adr_matches_table_157() {
        // CONTROL in the upper nibble, ADR in the lower.
        assert_eq!(CTL_ADR_AUDIO, 0x01, "2 audio channels, copy prohibited, ADR=1");
        assert_eq!(CTL_ADR_AUDIO_COPY_PERMITTED, 0x21, "copy bit is CONTROL bit 5");
    }

    #[test]
    fn the_lead_in_entry_matches_the_specifications_sample() {
        // Table 155 row "00 (lead-in)": 01 00 00 01 00 00 00 00.
        let sheet = build_cue_sheet(&[CueTrack::new(75 * 60)], None, None, true);
        assert_eq!(&sheet[..ENTRY_BYTES], &[0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00]);
    }

    #[test]
    fn the_first_pause_entry_matches_the_specifications_sample() {
        // Table 155 row "08 (TNO:01)": 01 01 00 01 00 00 00 00.
        let sheet = build_cue_sheet(&[CueTrack::new(75 * 60)], None, None, true);
        assert_eq!(
            &sheet[ENTRY_BYTES..ENTRY_BYTES * 2],
            &[0x01, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00],
        );
    }

    #[test]
    fn track_one_starts_two_seconds_in_like_the_sample() {
        // Table 155 row "10 (TNO:01)": 01 01 01 00 00 00 02 00.
        let sheet = build_cue_sheet(&[CueTrack::new(75 * 60)], None, None, true);
        assert_eq!(
            &sheet[ENTRY_BYTES * 2..ENTRY_BYTES * 3],
            &[0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x02, 0x00],
        );
    }

    #[test]
    fn cd_text_only_changes_the_lead_in_entry() {
        let plain = build_cue_sheet(&[CueTrack::new(300)], None, None, true);
        let texted = build_cue_sheet(&[CueTrack::new(300)], Some(Msf::from_sector(0)), None, true);
        assert_eq!(plain.len(), texted.len());
        assert_eq!(plain[3], DATA_FORM_GENERATED);
        assert_eq!(texted[3], DATA_FORM_LEADIN_CD_TEXT);
        // Every other byte is identical.
        assert_eq!(&plain[4..], &texted[4..]);
        assert_eq!(&plain[..3], &texted[..3]);
    }

    #[test]
    fn tracks_are_laid_end_to_end_after_the_pregap() {
        let sheet = build_cue_sheet(
            &[CueTrack::new(300), CueTrack::new(450), CueTrack::new(600)],
            None,
            None,
            true,
        );
        let entries = parse(&sheet);
        // lead-in, pause, three tracks, lead-out
        assert_eq!(entries.len(), 6);
        assert_eq!(entries[2].address.to_sector(), 150);
        assert_eq!(entries[3].address.to_sector(), 150 + 300);
        assert_eq!(entries[4].address.to_sector(), 150 + 300 + 450);
        assert_eq!(entries[5].address.to_sector(), 150 + 300 + 450 + 600);
    }

    #[test]
    fn the_lead_in_entry_carries_the_discs_real_lead_in_start() {
        // A blank CD-R reports its lead-in start from ATIP, typically around
        // 97 minutes. The drive needs that address, not zero.
        let start = Msf { minute: 97, second: 27, frame: 8 };
        let sheet = build_cue_sheet(&[CueTrack::new(300)], Some(start), None, true);
        let lead_in = parse(&sheet)[0];
        assert_eq!(lead_in.data_form, DATA_FORM_LEADIN_CD_TEXT);
        assert_eq!(lead_in.address, start);
    }

    #[test]
    fn the_lead_out_is_track_aa_at_index_one() {
        let sheet = build_cue_sheet(&[CueTrack::new(300)], None, None, true);
        let last = *parse(&sheet).last().expect("a lead-out entry");
        assert_eq!(last.track, LEAD_OUT_TRACK);
        assert_eq!(last.index, 0x01, "note 3: always 01h for lead-out");
        assert_eq!(last.data_form, DATA_FORM_GENERATED);
    }

    #[test]
    fn track_numbers_run_from_one_upwards() {
        let tracks: Vec<CueTrack> = (0..12).map(|_| CueTrack::new(300)).collect();
        let entries = parse(&build_cue_sheet(&tracks, Some(Msf::from_sector(0)), None, true));
        let numbered: Vec<u8> = entries
            .iter()
            .filter(|e| e.index == 0x01 && e.track != LEAD_OUT_TRACK)
            .map(|e| e.track)
            .collect();
        assert_eq!(numbered, (1..=12).collect::<Vec<u8>>());
    }

    #[test]
    fn the_sheet_is_a_whole_number_of_entries() {
        for count in [1, 2, 12, 99] {
            let tracks: Vec<CueTrack> = (0..count).map(|_| CueTrack::new(300)).collect();
            let sheet = build_cue_sheet(&tracks, Some(Msf::from_sector(0)), None, true);
            assert_eq!(sheet.len() % ENTRY_BYTES, 0);
            // lead-in + pause + tracks + lead-out
            assert_eq!(sheet.len() / ENTRY_BYTES, count + 3);
        }
    }

    #[test]
    fn without_isrc_or_a_catalog_the_sheet_is_unchanged() {
        // The shape that burns correctly today must not move when the feature
        // is present but unused.
        let plain = build_cue_sheet(&[CueTrack::new(300)], Some(Msf::from_sector(0)), None, true);
        let with_empty = build_cue_sheet(
            &[CueTrack { sectors: 300, isrc: Some(String::new()) }],
            Some(Msf::from_sector(0)),
            Some(""),
            true,
        );
        assert_eq!(plain, with_empty);
    }

    #[test]
    fn the_catalog_number_leads_the_sheet_across_two_entries() {
        let sheet = build_cue_sheet(
            &[CueTrack::new(300)],
            Some(Msf::from_sector(0)),
            Some("1234567890123"),
            true,
        );
        let entries = parse(&sheet);
        assert_eq!(entries[0].ctl_adr & 0x0F, ADR_CATALOG);
        assert_eq!(entries[1].ctl_adr & 0x0F, ADR_CATALOG);
        // Seven characters, then six.
        assert_eq!(&sheet[1..8], b"1234567");
        assert_eq!(&sheet[9..15], b"890123");
        assert_eq!(sheet[15], 0, "the spare byte stays zero");
        // The lead-in still follows.
        assert_eq!(entries[2].track, 0x00);
    }

    #[test]
    fn a_tracks_isrc_immediately_precedes_it() {
        let sheet = build_cue_sheet(
            &[
                CueTrack { sectors: 300, isrc: Some("GBAYE0000351".into()) },
                CueTrack::new(300),
            ],
            Some(Msf::from_sector(0)),
            None,
            true,
        );
        let entries = parse(&sheet);
        // lead-in, pause, [isrc, isrc], track 1, track 2, lead-out
        let isrc: Vec<&CueEntry> = entries.iter().filter(|e| e.ctl_adr & 0x0F == ADR_ISRC).collect();
        assert_eq!(isrc.len(), 2, "an ISRC is two entries");
        assert!(isrc.iter().all(|e| e.track == 1));

        let position = entries.iter().position(|e| e.ctl_adr & 0x0F == ADR_ISRC).expect("isrc");
        let track_one = entries
            .iter()
            .position(|e| e.index == 0x01 && e.track == 1)
            .expect("track 1");
        assert_eq!(position + 2, track_one, "the pair sits directly before its track");
    }

    #[test]
    fn the_isrc_characters_are_carried_in_order() {
        let sheet = build_cue_sheet(
            &[CueTrack { sectors: 300, isrc: Some("GBAYE0000351".into()) }],
            Some(Msf::from_sector(0)),
            None,
            true,
        );
        let start = sheet
            .as_chunks::<ENTRY_BYTES>()
            .0
            .iter()
            .position(|c| c[0] & 0x0F == ADR_ISRC)
            .expect("isrc entry")
            * ENTRY_BYTES;
        assert_eq!(&sheet[start + 2..start + 8], b"GBAYE0");
        assert_eq!(&sheet[start + ENTRY_BYTES + 2..start + ENTRY_BYTES + 8], b"000351");
    }

    #[test]
    fn a_malformed_code_is_dropped_rather_than_truncated() {
        // Half an ISRC on a disc is worse than none.
        for bad in ["SHORT", "WAYTOOLONGFORANISRC", "GB-AYE-00-003", ""] {
            let sheet = build_cue_sheet(
                &[CueTrack { sectors: 300, isrc: Some(bad.into()) }],
                Some(Msf::from_sector(0)),
                Some(bad),
                true,
            );
            assert!(
                !parse(&sheet).iter().any(|e| matches!(e.ctl_adr & 0x0F, ADR_ISRC | ADR_CATALOG)),
                "{bad:?} should not have been encoded"
            );
        }
    }

    #[test]
    fn a_full_disc_stays_inside_a_typical_cue_sheet_limit() {
        // Drives report a maximum cue sheet length; 99 tracks must fit the
        // smallest figure seen in the wild with room to spare.
        let tracks: Vec<CueTrack> = (0..99).map(|_| CueTrack::new(300)).collect();
        assert!(build_cue_sheet(&tracks, Some(Msf::from_sector(0)), None, true).len() < 1024);
    }

    // ── Gapped discs ────────────────────────────────────────────────────

    /// Three tracks with distinct lengths, so a misplaced address cannot pass
    /// for a correct one.
    fn three_tracks() -> Vec<CueTrack> {
        vec![CueTrack::new(300), CueTrack::new(450), CueTrack::new(600)]
    }

    #[test]
    fn a_gapped_disc_pauses_before_every_track_but_the_first() {
        let entries = parse(&build_cue_sheet(&three_tracks(), None, None, false));
        // lead-in, track 1's pregap and audio, then a pause and audio for each
        // of tracks 2 and 3, then the lead-out.
        assert_eq!(entries.len(), 8);

        let shape: Vec<(u8, u8, u32)> = entries[1..entries.len() - 1]
            .iter()
            .map(|e| (e.track, e.index, e.address.to_sector()))
            .collect();
        assert_eq!(
            shape,
            vec![
                (1, 0x00, 0),
                (1, 0x01, 150),
                (2, 0x00, 150 + 300),
                (2, 0x01, 150 + 300 + 150),
                (3, 0x00, 150 + 300 + 150 + 450),
                (3, 0x01, 150 + 300 + 150 + 450 + 150),
            ],
        );
    }

    #[test]
    fn a_gapless_disc_is_the_sheet_that_burns_today() {
        // The shape hardware has already been burned against, byte for byte:
        // no index 0 but track 1's, and tracks end to end from 00:02:00.
        let entries = parse(&build_cue_sheet(&three_tracks(), None, None, true));
        assert_eq!(entries.len(), 6);
        assert!(entries[2..5].iter().all(|e| e.index == 0x01));
        assert_eq!(entries[2].address.to_sector(), 150);
        assert_eq!(entries[3].address.to_sector(), 150 + 300);
        assert_eq!(entries[4].address.to_sector(), 150 + 300 + 450);
        assert_eq!(entries[5].address.to_sector(), 150 + 300 + 450 + 600);
    }

    #[test]
    fn track_one_keeps_its_mandatory_pregap_either_way() {
        // Gapless removes the gaps *between* tracks and nothing else: the
        // two-second pause before track 1 is required by Red Book.
        for gapless in [true, false] {
            let entries = parse(&build_cue_sheet(&three_tracks(), None, None, gapless));
            assert_eq!((entries[1].track, entries[1].index), (1, 0x00));
            assert_eq!(entries[1].address.to_sector(), 0);
            assert_eq!(entries[1].data_form, DATA_FORM_GENERATED);
            assert_eq!((entries[2].track, entries[2].index), (1, 0x01));
            assert_eq!(entries[2].address.to_sector(), 150);
        }
    }

    #[test]
    fn a_pause_is_generated_by_the_drive_so_no_audio_is_transferred_for_it() {
        // DATA FORM `00h` is the only form the host sends bytes for, so the
        // number of those entries is the length of the WRITE(10) stream in
        // tracks. Gapping a disc must not add one.
        for gapless in [true, false] {
            let entries = parse(&build_cue_sheet(&three_tracks(), None, None, gapless));
            let from_host = entries.iter().filter(|e| e.data_form == DATA_FORM_AUDIO).count();
            assert_eq!(from_host, 3, "one host-supplied region per track");
            assert!(
                entries.iter().all(|e| e.index != 0x00 || e.data_form == DATA_FORM_GENERATED),
                "every pause is the drive's to write"
            );
        }
    }

    #[test]
    fn the_lead_out_moves_by_one_pause_per_gap() {
        // The audio is the same either way; the disc is 150 sectors longer for
        // every gap, and the lead-out is where that shows up.
        for count in [1_u32, 2, 12, 99] {
            let tracks: Vec<CueTrack> = (0..count).map(|_| CueTrack::new(300)).collect();
            let audio = PREGAP_SECTORS + count * 300;
            let gapless = parse(&build_cue_sheet(&tracks, None, None, true));
            let gapped = parse(&build_cue_sheet(&tracks, None, None, false));
            assert_eq!(gapless.last().expect("lead-out").address.to_sector(), audio);
            assert_eq!(
                gapped.last().expect("lead-out").address.to_sector(),
                audio + PREGAP_SECTORS * (count - 1),
            );
        }
    }

    #[test]
    fn a_single_track_disc_is_the_same_sheet_either_way() {
        // With nothing to sit between, there is no gap to add.
        let one = [CueTrack::new(300)];
        assert_eq!(
            build_cue_sheet(&one, Some(Msf::from_sector(0)), None, true),
            build_cue_sheet(&one, Some(Msf::from_sector(0)), None, false),
        );
    }

    #[test]
    fn a_gap_costs_exactly_one_entry() {
        for count in [1, 2, 12, 99] {
            let tracks: Vec<CueTrack> = (0..count).map(|_| CueTrack::new(300)).collect();
            let sheet = build_cue_sheet(&tracks, Some(Msf::from_sector(0)), None, false);
            assert_eq!(sheet.len() % ENTRY_BYTES, 0);
            // lead-in + pause + tracks + lead-out, plus a pause per gap.
            assert_eq!(sheet.len() / ENTRY_BYTES, count + 3 + (count - 1));
        }
    }

    #[test]
    fn an_isrc_still_sits_directly_before_its_tracks_audio_when_gapped() {
        let sheet = build_cue_sheet(
            &[
                CueTrack::new(300),
                CueTrack { sectors: 300, isrc: Some("GBAYE0000351".into()) },
            ],
            Some(Msf::from_sector(0)),
            None,
            false,
        );
        let entries = parse(&sheet);
        let isrc = entries
            .iter()
            .position(|e| e.ctl_adr & 0x0F == ADR_ISRC)
            .expect("isrc");
        let audio = entries
            .iter()
            .position(|e| e.index == 0x01 && e.track == 2)
            .expect("track 2");
        assert_eq!(isrc + 2, audio, "the pair sits between the pause and the audio");
        assert_eq!(entries[isrc - 1].index, 0x00, "track 2's pause comes first");
        assert_eq!(entries[isrc - 1].track, 2);
    }
}
