//! Session-At-Once writing with a CD-TEXT lead-in (Windows).
//!
//! IMAPI2 has no CD-TEXT support, so this path drives the recorder itself
//! through `IDiscRecorder2Ex::SendCommand*` — still inside IMAPI2, so it runs
//! unelevated and keeps IMAPI2's exclusive-access handling.
//!
//! Confirmed working against real hardware. The three things that had to be
//! right, and were not obvious:
//!
//! 1. The lead-in DATA FORM is `41h` — raw P-W from the host, main channel
//!    generated by the drive.
//! 2. The lead-in is **the whole lead-in**, from the disc's ATIP start (around
//!    97 minutes, so ~13 500 sectors) up to the pregap at −150, with the pack
//!    sequence repeated to fill it. Writing only enough sectors to hold the
//!    packs once produces a disc whose CD-TEXT cannot be read back.
//! 3. The cue sheet's lead-in entry carries the disc's real lead-in start,
//!    read from `READ DISC INFORMATION`, not zero.
//!
//! **The whole design turns on one boundary.** Everything up to and including
//! `SEND CUE SHEET` is negotiation: if the drive refuses any of it, nothing has
//! touched the disc and the caller falls back to the IMAPI2 path that is known
//! to work. From the first `WRITE(10)` onwards the session is being burned and
//! there is no way back. `SaoError` names which side of that line a failure
//! happened on, and the caller must respect it.

use std::fs::File;
use std::io::Read;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use tauri::AppHandle;
use windows::Win32::Storage::Imapi::{
    IDiscRecorder2, IDiscRecorder2Ex, IMAPI_MODE_PAGE_REQUEST_TYPE_CURRENT_VALUES,
    IMAPI_MODE_PAGE_TYPE_WRITE_PARAMETERS,
};
use windows::Win32::System::Com::CoTaskMemFree;
use windows_core::Interface;

use crate::cdtext::{CdTextBlock, SUBCHANNEL_BYTES_PER_SECTOR};
use crate::job::{emit_progress, PROGRESS_THROTTLE_MS};
use crate::mmc::cue::{build_cue_sheet, CueTrack, Msf, PREGAP_SECTORS};
use crate::mmc::mode::{self, WriteParameters};
use crate::mmc::{
    lead_in_sectors, lead_in_start_lba, read_disc_information_cdb, sectors_per_second_to_kbps,
    send_cue_sheet_cdb, set_cd_speed_cdb, write_10_cdb,
};
use crate::model::{BurnPhase, CdTextVerification, BYTES_PER_AUDIO_SECTOR};
use crate::render::RenderedTrack;

/// Bytes in one Red Book audio sector as the cue sheet's DATA FORM `00h`
/// describes it: 2352 of main data, subcode generated by the drive.
const MAIN_BYTES: usize = BYTES_PER_AUDIO_SECTOR;

/// Sectors per `WRITE(10)`. 27 × 2352 is just under 64 KB, which every drive
/// accepts; the real limit is queried and this is only the cap.
const DEFAULT_CHUNK_SECTORS: usize = 27;

/// Command timeouts, in seconds.
const TIMEOUT_SETUP: u32 = 30;
const TIMEOUT_WRITE: u32 = 300;

/// Which side of the point of no return a failure happened on.
#[derive(Debug)]
pub enum SaoError {
    /// The drive refused the setup. Nothing was written; falling back to the
    /// IMAPI2 path is safe and the disc is untouched.
    Setup(String),
    /// The burn had already begun. The disc is spoiled; do not retry onto it.
    Write(String),
}

impl std::fmt::Display for SaoError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SaoError::Setup(message) | SaoError::Write(message) => write!(f, "{message}"),
        }
    }
}

/// Decode a fixed-format sense buffer into something a person can act on.
fn sense_text(sense: &[u8; 18]) -> String {
    let key = sense[2] & 0x0F;
    let asc = sense[12];
    let ascq = sense[13];
    let meaning = match (key, asc, ascq) {
        (0x05, 0x24, _) => "the drive rejected a field in the command",
        (0x05, 0x26, _) => "the drive rejected a parameter value",
        (0x05, 0x20, _) => "the drive does not support that command",
        (0x02, 0x3A, _) => "there is no disc in the drive",
        (0x03, 0x0C, _) => "a write error on the disc",
        (0x04, _, _) => "a hardware fault in the drive",
        (0x0B, 0x08, _) => "the drive lost its data stream (buffer underrun)",
        _ => "the drive reported an error",
    };
    format!("{meaning} (sense {key:X}/{asc:02X}/{ascq:02X})")
}

/// One `WRITE(10)`'s worth of the program area.
struct Chunk {
    /// Sectors to step the write address over before this chunk: the pause the
    /// drive generates between two tracks. Nothing is transferred for it, but
    /// it takes up the addresses in between.
    skip: u32,
    /// Audio bytes waiting in the buffer. Whole sectors, unless a rendered
    /// file was truncated — which `write_program_area` tests for before it
    /// writes.
    bytes: usize,
}

/// Feeds the program area 2352-byte sectors, track after track.
struct SectorSource {
    files: Vec<File>,
    current: usize,
    /// The pause before each track after the first — zero when the user asked
    /// for a gapless disc, which is what makes the tracks run together.
    gap_sectors: u32,
    /// A pause the next chunk must start after.
    pending_gap: u32,
}

impl SectorSource {
    fn open(tracks: &[RenderedTrack], gap_sectors: u32) -> Result<Self, String> {
        let files = tracks
            .iter()
            .map(|track| {
                File::open(&track.path)
                    .map_err(|e| format!("cannot read {}: {e}", track.path.display()))
            })
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Self { files, current: 0, gap_sectors, pending_gap: 0 })
    }

    /// Fill `buffer` with whole sectors and say where they belong.
    ///
    /// A file that reads back nothing is the end of that track, not of the
    /// chunk: the next track carries straight on filling the same buffer, and
    /// it still lands on a sector boundary because rendering padded every
    /// track out to a whole one.
    ///
    /// A chunk never straddles a gap. A pause leaves 150 sectors between the
    /// tail of one track and the head of the next, and a `WRITE(10)` addresses
    /// one unbroken run, so the tail is written on its own and the pause is
    /// handed to the caller as `skip`. With no gap the tracks are contiguous
    /// and a chunk is filled from as many files as it takes, which is what
    /// keeps the drive fed.
    fn read(&mut self, buffer: &mut [u8]) -> Result<Chunk, String> {
        let mut skip = std::mem::take(&mut self.pending_gap);
        let mut filled = 0;
        while filled < buffer.len() && self.current < self.files.len() {
            let read = self.files[self.current]
                .read(&mut buffer[filled..])
                .map_err(|e| format!("reading rendered audio failed: {e}"))?;
            if read > 0 {
                filled += read;
                continue;
            }
            // This track's file is spent; the next one continues the disc.
            self.current += 1;
            if self.current < self.files.len() {
                self.pending_gap += self.gap_sectors;
            }
            if self.pending_gap == 0 {
                continue;
            }
            if filled == 0 {
                // Nothing is buffered yet, so this chunk can start after the
                // pause instead of leaving an empty one behind — a chunk of no
                // bytes is how the caller knows the disc is finished.
                skip += std::mem::take(&mut self.pending_gap);
                continue;
            }
            break;
        }
        Ok(Chunk { skip, bytes: filled })
    }
}

/// Write the whole session, optionally with a CD-TEXT lead-in.
///
/// Returns the number of program-area sectors written.
#[allow(clippy::too_many_arguments)] // One write; bundling would only move the arity.
pub fn write_session(
    app: &AppHandle,
    job_id: &str,
    recorder: &IDiscRecorder2,
    tracks: &[RenderedTrack],
    cd_text: Option<&CdTextBlock>,
    catalog: Option<&str>,
    gapless: bool,
    test_write: bool,
    buffer_underrun_free: bool,
    // Sectors per second, or `None` to leave the choice to the drive.
    write_speed: Option<u32>,
    cancel: &Arc<AtomicBool>,
) -> Result<u32, SaoError> {
    let ex = recorder
        .cast::<IDiscRecorder2Ex>()
        .map_err(|e| SaoError::Setup(format!("this drive exposes no command interface: {e}")))?;

    // ── Negotiation. Nothing below writes to the disc. ───────────────────
    configure_write_parameters(&ex, cd_text.is_some(), test_write, buffer_underrun_free)?;
    set_write_speed(&ex, write_speed);

    // ISRC rides in the cue sheet on this path — the IMAPI2 path sets it via
    // IRawCDImageTrackInfo, and for a while this one silently dropped it.
    let cue_tracks: Vec<CueTrack> = tracks
        .iter()
        .map(|track| CueTrack { sectors: track.sectors, isrc: track.isrc.clone() })
        .collect();
    // The lead-in geometry has to be known before the cue sheet, which
    // announces where the lead-in starts.
    let lead_in = match cd_text {
        Some(_) => Some(read_lead_in(&ex)?),
        None => None,
    };
    // Gapless rides in the cue sheet too. IMAPI2 has its own switch for it, so
    // until this argument existed, turning CD-TEXT on moved the burn to this
    // path and quietly dropped the two-second pause before every track after
    // the first — the same queue, the same settings, a different disc.
    let sheet = build_cue_sheet(
        &cue_tracks,
        lead_in.as_ref().map(|l| l.start),
        catalog,
        gapless,
    );
    send_cue_sheet(&ex, &sheet)?;

    if cancel.load(Ordering::Relaxed) {
        return Err(SaoError::Setup("cancelled".to_string()));
    }

    // ── Past this line the laser is on. ──────────────────────────────────
    //
    // The audio, and only the audio: the drive generates the pauses, so this
    // is the length of the WRITE(10) stream whether or not the disc is gapped.
    // The disc itself is longer than this by 150 sectors per gap, which is the
    // cue sheet's business and not the transfer's.
    let sectors_total: u32 = tracks.iter().map(|track| track.sectors).sum();
    let chunk_sectors = max_chunk_sectors(&ex);

    if let (Some(block), Some(lead_in)) = (cd_text, lead_in.as_ref()) {
        write_cd_text_lead_in(&ex, block, lead_in, chunk_sectors)?;
    }

    let written = write_program_area(
        app,
        job_id,
        &ex,
        tracks,
        sectors_total,
        chunk_sectors,
        gapless,
        cancel,
    )?;

    synchronize_cache(&ex)?;
    Ok(written)
}

/// Read the Write Parameters page, edit it, and hand it back.
fn configure_write_parameters(
    ex: &IDiscRecorder2Ex,
    cd_text: bool,
    test_write: bool,
    buffer_underrun_free: bool,
) -> Result<(), SaoError> {
    let mut data: *mut u8 = std::ptr::null_mut();
    let mut size: u32 = 0;

    // SAFETY: IMAPI2 allocates the page with the COM allocator; freed below.
    let read = unsafe {
        ex.GetModePage(
            IMAPI_MODE_PAGE_TYPE_WRITE_PARAMETERS,
            IMAPI_MODE_PAGE_REQUEST_TYPE_CURRENT_VALUES,
            &raw mut data,
            &raw mut size,
        )
    };

    let page = if read.is_ok() && !data.is_null() && size > 0 {
        // SAFETY: IMAPI2 reported `size` valid bytes at `data`.
        unsafe { std::slice::from_raw_parts(data, size as usize) }.to_vec()
    } else {
        Vec::new()
    };
    if !data.is_null() {
        // SAFETY: allocated by IMAPI2 with the COM task allocator.
        unsafe { CoTaskMemFree(Some(data.cast())) };
    }

    if page.is_empty() {
        return Err(SaoError::Setup(
            "the drive would not report its write settings".to_string(),
        ));
    }

    let edited = mode::apply(
        &page,
        WriteParameters { test_write, buffer_underrun_free, raw_subchannel: cd_text },
    )
    .map_err(|e| SaoError::Setup(e.to_string()))?;

    // SAFETY: `edited` is the drive's own page with a few fields changed.
    unsafe { ex.SetModePage(IMAPI_MODE_PAGE_REQUEST_TYPE_CURRENT_VALUES, &edited) }.map_err(
        |e| {
            SaoError::Setup(format!(
                "the drive rejected Session-At-Once settings, so CD-TEXT is not possible on it: {e}"
            ))
        },
    )
}

/// Ask the drive to burn at the speed the user picked.
///
/// Best-effort, and deliberately so — the same bargain the IMAPI2 path makes
/// with `let _ = format.SetWriteSpeed(..)`. A drive that will not take the
/// command still burns the disc, at whatever speed it likes; refusing to burn
/// over it would be a worse answer than a fast disc.
///
/// `None` is the default, and it must stay silent: a user who has not chosen a
/// speed gets the command stream this path has always sent, byte for byte.
/// That is also why this sits up here in the negotiation, before `SEND CUE
/// SHEET` — a rejection here cannot cost a disc, and MMC-3 6.35 applies the
/// speed to the write that follows.
fn set_write_speed(ex: &IDiscRecorder2Ex, write_speed: Option<u32>) {
    let Some(sectors) = write_speed.filter(|sectors| *sectors > 0) else {
        return;
    };
    let Some(kbps) = sectors_per_second_to_kbps(sectors) else {
        crate::app_eprintln!(
            "[burn] {sectors} sectors/s is not a write speed a drive could take; letting it choose"
        );
        return;
    };

    let cdb = set_cd_speed_cdb(kbps);
    let mut sense = [0_u8; 18];
    // SAFETY: a no-data command; the drive writes only into `sense`.
    match unsafe { ex.SendCommandNoData(&cdb, &mut sense, TIMEOUT_SETUP) } {
        Ok(()) => crate::app_deprintln!(
            "[burn] write speed set to {kbps} kB/s ({sectors} sectors/s)"
        ),
        Err(error) => crate::app_eprintln!(
            "[burn] the drive would not take a write speed of {kbps} kB/s, letting it choose: {} ({error})",
            sense_text(&sense)
        ),
    }
}

fn send_cue_sheet(ex: &IDiscRecorder2Ex, sheet: &[u8]) -> Result<(), SaoError> {
    let cdb = send_cue_sheet_cdb(sheet.len() as u32);
    let mut sense = [0_u8; 18];
    // SAFETY: cdb and sheet outlive the call; sense is written by the drive.
    unsafe { ex.SendCommandSendDataToDevice(&cdb, &mut sense, TIMEOUT_SETUP, sheet) }.map_err(
        |e| {
            SaoError::Setup(format!(
                "the drive rejected the disc layout: {} ({e})",
                sense_text(&sense)
            ))
        },
    )
}

/// Sectors per write, clamped to what the drive will accept.
///
/// Sized against the audio sector, which is the larger of the two block sizes
/// in play, so the same figure is safe for the 96-byte lead-in blocks too.
fn max_chunk_sectors(ex: &IDiscRecorder2Ex) -> usize {
    // SAFETY: a plain property read on the recorder.
    let limit = unsafe { ex.GetMaximumNonPageAlignedTransferSize() }.unwrap_or(0) as usize;
    if limit == 0 {
        return DEFAULT_CHUNK_SECTORS;
    }
    (limit / MAIN_BYTES).clamp(1, DEFAULT_CHUNK_SECTORS)
}

/// Where this disc's lead-in begins, and how long it is.
///
/// Read from `READ DISC INFORMATION` (bytes 17-19 hold the lead-in start as
/// MSF). Both numbers matter: the cue sheet announces the start, and the write
/// has to cover the whole extent.
struct LeadIn {
    start: Msf,
    sectors: u32,
}

fn read_lead_in(ex: &IDiscRecorder2Ex) -> Result<LeadIn, SaoError> {
    let mut buffer = [0_u8; 34];
    let cdb = read_disc_information_cdb(buffer.len() as u16);
    let mut sense = [0_u8; 18];
    let mut fetched: u32 = 0;

    // SAFETY: a read of at most `buffer.len()` bytes into our own buffer.
    unsafe {
        ex.SendCommandGetDataFromDevice(
            &cdb,
            &mut sense,
            TIMEOUT_SETUP,
            &mut buffer,
            &raw mut fetched,
        )
    }
    .map_err(|e| {
        SaoError::Setup(format!(
            "the drive would not describe the disc: {} ({e})",
            sense_text(&sense)
        ))
    })?;

    if (fetched as usize) < 20 {
        return Err(SaoError::Setup(
            "the drive returned no lead-in address for this disc".to_string(),
        ));
    }

    let start = Msf { minute: buffer[17], second: buffer[18], frame: buffer[19] };
    let sectors = lead_in_sectors(start.to_sector());
    crate::app_deprintln!(
        "[burn] lead-in starts at {:02}:{:02}:{:02} ({} sectors)",
        start.minute,
        start.second,
        start.frame,
        sectors
    );
    Ok(LeadIn { start, sectors })
}

/// Write the CD-TEXT into the lead-in.
///
/// The lead-in is **not** just long enough to hold the packs once. It runs from
/// the disc's ATIP lead-in start (typically ~97 minutes, so ~13 500 sectors) up
/// to the pregap at −150, and the pack sequence is **repeated over and over**
/// to fill the whole of it. That repetition is the point: a player picks the
/// text up wherever in the lead-in it happens to start reading.
///
/// Writing only enough sectors for one pass leaves a lead-in the drive has to
/// make up the rest of, and the text is not there to be read back.
fn write_cd_text_lead_in(
    ex: &IDiscRecorder2Ex,
    block: &CdTextBlock,
    lead_in: &LeadIn,
    chunk_sectors: usize,
) -> Result<(), SaoError> {
    let subchannel = block.to_subchannel();
    let source_sectors = block.sector_count();
    if source_sectors == 0 || lead_in.sectors == 0 {
        return Ok(());
    }

    let mut lba = lead_in_start_lba(lead_in.sectors);
    let mut remaining = lead_in.sectors as usize;
    // One cycling read position through the pack sectors.
    let mut cursor = 0_usize;
    let mut buffer = vec![0_u8; chunk_sectors * SUBCHANNEL_BYTES_PER_SECTOR];

    crate::app_deprintln!(
        "[burn] writing {} lead-in sectors from LBA {} ({} sectors of CD-TEXT, repeated)",
        lead_in.sectors,
        lba,
        source_sectors
    );

    while remaining > 0 {
        let sectors = remaining.min(chunk_sectors);
        for slot in 0..sectors {
            let from = cursor * SUBCHANNEL_BYTES_PER_SECTOR;
            let to = slot * SUBCHANNEL_BYTES_PER_SECTOR;
            buffer[to..to + SUBCHANNEL_BYTES_PER_SECTOR]
                .copy_from_slice(&subchannel[from..from + SUBCHANNEL_BYTES_PER_SECTOR]);
            cursor = (cursor + 1) % source_sectors;
        }

        let cdb = write_10_cdb(lba, sectors as u16);
        let payload = &buffer[..sectors * SUBCHANNEL_BYTES_PER_SECTOR];
        write_with_backoff(ex, &cdb, payload).map_err(|reason| {
            SaoError::Write(format!("writing the CD-TEXT lead-in failed: {reason}"))
        })?;

        lba += sectors as i32;
        remaining -= sectors;
    }
    Ok(())
}

/// Send one `WRITE(10)`, waiting out a full drive buffer rather than failing.
///
/// A drive that cannot take more data reports Not Ready / "long write in
/// progress" (sense `2/04/08`). That is back-pressure, not an error — the only
/// correct response is to wait and try the same block again. Treating it as a
/// failure would abort a burn mid-disc for no reason, and writing a whole
/// lead-in makes hitting it near-certain.
fn write_with_backoff(
    ex: &IDiscRecorder2Ex,
    cdb: &[u8; 10],
    payload: &[u8],
) -> Result<(), String> {
    /// Long enough to matter, short enough not to starve the drive.
    const BACKOFF: Duration = Duration::from_millis(40);
    /// 1000 attempts, sleeping `BACKOFF` after each refusal: 40 seconds of
    /// waiting out a full buffer before the burn is given up on.
    const MAX_RETRIES: u32 = 1000;

    for _ in 0..MAX_RETRIES {
        let mut sense = [0_u8; 18];
        // SAFETY: `payload` outlives the call; sense is written by the drive.
        let result = unsafe { ex.SendCommandSendDataToDevice(cdb, &mut sense, TIMEOUT_WRITE, payload) };
        match result {
            Ok(()) => return Ok(()),
            Err(error) => {
                let key = sense[2] & 0x0F;
                if key == 0x02 && sense[12] == 0x04 && sense[13] == 0x08 {
                    std::thread::sleep(BACKOFF);
                    continue;
                }
                return Err(format!("{} ({error})", sense_text(&sense)));
            }
        }
    }
    Err("the drive stayed busy for too long".to_string())
}

#[allow(clippy::too_many_arguments)] // One write; bundling would only move the arity.
fn write_program_area(
    app: &AppHandle,
    job_id: &str,
    ex: &IDiscRecorder2Ex,
    tracks: &[RenderedTrack],
    sectors_total: u32,
    chunk_sectors: usize,
    gapless: bool,
    cancel: &Arc<AtomicBool>,
) -> Result<u32, SaoError> {
    // The pause between two tracks is the drive's to write, exactly like the
    // pregap before track 1: it never reaches this buffer, only the address.
    let gap_sectors = if gapless { 0 } else { PREGAP_SECTORS };
    let mut source = SectorSource::open(tracks, gap_sectors).map_err(SaoError::Write)?;
    let mut buffer = vec![0_u8; chunk_sectors * MAIN_BYTES];
    let mut lba: i32 = 0;
    let mut written: u32 = 0;
    let mut last_emit = 0_u64;

    loop {
        if cancel.load(Ordering::Relaxed) {
            // The disc is already spoiled, but stopping the laser sooner is
            // still better than burning the rest of it.
            return Err(SaoError::Write("cancelled".to_string()));
        }

        let chunk = source.read(&mut buffer).map_err(SaoError::Write)?;
        if chunk.bytes == 0 {
            break;
        }
        // Rendering pads every track to a sector boundary, so a partial
        // sector here means a truncated file. On a gapped disc it can arrive
        // in the middle of the queue as well as at the end, because a chunk
        // stops at a pause instead of running on into the next file. Writing
        // the whole sectors and dropping the tail would start every later
        // track a sector early and finish the session short of the lead-out
        // the cue sheet has already announced, with the drive still waiting
        // for audio, so stop instead.
        if !chunk.bytes.is_multiple_of(MAIN_BYTES) {
            return Err(SaoError::Write(
                "the rendered audio ended mid-sector; the burn cannot continue".to_string(),
            ));
        }

        // Step over the pause before this track. The drive writes those
        // sectors from its own silence, so they are addresses to us and
        // nothing else — the same jump the lead-in write makes when it stops
        // at −151 and leaves the pregap to the drive.
        lba += chunk.skip as i32;

        let sectors = (chunk.bytes / MAIN_BYTES) as u16;
        let cdb = write_10_cdb(lba, sectors);
        write_with_backoff(ex, &cdb, &buffer[..chunk.bytes])
            .map_err(|reason| SaoError::Write(format!("writing audio failed: {reason}")))?;

        lba += i32::from(sectors);
        written += u32::from(sectors);

        let now = epoch_ms();
        if u128::from(now.saturating_sub(last_emit)) >= PROGRESS_THROTTLE_MS {
            last_emit = now;
            emit_progress(
                app,
                job_id,
                BurnPhase::Writing,
                None,
                written.min(sectors_total),
                sectors_total,
                None,
            );
        }
    }

    Ok(written)
}

/// Flush the drive's cache so the session is complete before we let go.
fn synchronize_cache(ex: &IDiscRecorder2Ex) -> Result<(), SaoError> {
    const OP_SYNCHRONIZE_CACHE: u8 = 0x35;
    let cdb = [OP_SYNCHRONIZE_CACHE, 0, 0, 0, 0, 0, 0, 0, 0, 0];
    let mut sense = [0_u8; 18];
    let started = Instant::now();
    // SAFETY: a no-data command; the drive may take a while to finalise.
    let result = unsafe { ex.SendCommandNoData(&cdb, &mut sense, TIMEOUT_WRITE) };
    crate::app_deprintln!("[burn] finalise took {:?}", started.elapsed());
    result.map_err(|e| {
        SaoError::Write(format!(
            "the drive could not finalise the disc: {} ({e})",
            sense_text(&sense)
        ))
    })
}

fn epoch_ms() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

// ── Read-back verification ───────────────────────────────────────────────────

/// Read the CD-TEXT the drive actually stored in the lead-in and say what was
/// found.
///
/// `READ TOC/PMA/ATIP` with format `0101b` returns the lead-in's CD-TEXT packs.
/// Two things this must never do: report "no CD-TEXT" when the drive simply
/// refused the query, and report success on a buffer of zeros. Only packs whose
/// CRC checks out are counted.
///
/// Note that a drive often caches the table of contents it read when the disc
/// was loaded. Immediately after a burn that cache can predate the lead-in we
/// just wrote, so a `checked: true, packs: 0` result straight after burning is
/// not proof the disc is blank — re-checking with the disc reloaded is.
pub fn verify_cd_text(recorder: &IDiscRecorder2) -> CdTextVerification {
    const OP_READ_TOC: u8 = 0x43;
    const FORMAT_CD_TEXT: u8 = 0x05;
    /// Big enough for a full block (255 packs) with room to spare, small
    /// enough that no drive balks at the allocation length.
    const BUFFER_BYTES: usize = 4 + 512 * crate::cdtext::PACK_BYTES;

    let Ok(ex) = recorder.cast::<IDiscRecorder2Ex>() else {
        return CdTextVerification::unreadable("this drive exposes no command interface");
    };

    let mut buffer = vec![0_u8; BUFFER_BYTES];
    let len = BUFFER_BYTES as u16;
    let cdb = [
        OP_READ_TOC,
        0,
        FORMAT_CD_TEXT,
        0,
        0,
        0,
        0,
        (len >> 8) as u8,
        len as u8,
        0,
    ];
    let mut sense = [0_u8; 18];
    let mut fetched: u32 = 0;

    // SAFETY: the drive writes at most `buffer.len()` bytes and reports how many.
    let read = unsafe {
        ex.SendCommandGetDataFromDevice(
            &cdb,
            &mut sense,
            TIMEOUT_SETUP,
            &mut buffer,
            &raw mut fetched,
        )
    };

    if let Err(error) = read {
        let detail = sense_text(&sense);
        crate::app_eprintln!("[burn] could not read CD-TEXT back: {detail} ({error})");
        return CdTextVerification::unreadable(format!(
            "the drive would not report the disc's CD-TEXT: {detail}"
        ));
    }

    // Header: two bytes of length (excluding themselves) then two reserved.
    let fetched = (fetched as usize).min(BUFFER_BYTES);
    if fetched <= 4 {
        crate::app_deprintln!("[burn] CD-TEXT read-back returned {fetched} bytes");
        return CdTextVerification::found(0);
    }

    let packs = crate::cdtext::count_valid_packs(&buffer[4..fetched]) as u32;
    crate::app_deprintln!("[burn] CD-TEXT read-back: {fetched} bytes, {packs} valid packs");
    CdTextVerification::found(packs)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::SECTORS_PER_SECOND;
    use std::io::Write;
    use std::path::Path;

    /// A rendered track whose every sector holds the same byte, so the audio
    /// can be told apart track by track once it has been chunked.
    fn rendered(dir: &Path, index: usize, sectors: u32) -> RenderedTrack {
        let path = dir.join(format!("track{index}.pcm"));
        File::create(&path)
            .and_then(|mut file| file.write_all(&vec![index as u8 + 1; sectors as usize * MAIN_BYTES]))
            .expect("write a rendered track");
        RenderedTrack {
            path,
            sectors,
            isrc: None,
            title: String::new(),
            artist: String::new(),
        }
    }

    /// Every `WRITE(10)` the program area would issue, as (LBA, sectors), plus
    /// the track byte of each sector in the order it was handed over.
    ///
    /// This is `write_program_area`'s loop with the drive taken out of it.
    fn writes(lengths: &[u32], gapless: bool) -> (Vec<(i32, u32)>, Vec<u8>) {
        let dir = tempfile::tempdir().expect("a temp dir");
        let tracks: Vec<RenderedTrack> = lengths
            .iter()
            .enumerate()
            .map(|(index, sectors)| rendered(dir.path(), index, *sectors))
            .collect();

        let gap_sectors = if gapless { 0 } else { PREGAP_SECTORS };
        let mut source = SectorSource::open(&tracks, gap_sectors).expect("open the tracks");
        let mut buffer = vec![0_u8; DEFAULT_CHUNK_SECTORS * MAIN_BYTES];
        let mut lba = 0_i32;
        let mut issued = Vec::new();
        let mut audio = Vec::new();

        loop {
            let chunk = source.read(&mut buffer).expect("read");
            if chunk.bytes == 0 {
                break;
            }
            assert!(chunk.bytes.is_multiple_of(MAIN_BYTES), "whole sectors only");
            lba += chunk.skip as i32;
            let sectors = (chunk.bytes / MAIN_BYTES) as u32;
            issued.push((lba, sectors));
            audio.extend(buffer[..chunk.bytes].iter().step_by(MAIN_BYTES));
            lba += sectors as i32;
        }
        (issued, audio)
    }

    /// The LBA each track's first sector landed on.
    fn track_starts(issued: &[(i32, u32)], lengths: &[u32]) -> Vec<i32> {
        let mut sectors: Vec<i32> = Vec::new();
        for (lba, count) in issued {
            sectors.extend((0..*count).map(|i| lba + i as i32));
        }
        let mut at = 0_usize;
        lengths
            .iter()
            .map(|length| {
                let start = sectors[at];
                at += *length as usize;
                start
            })
            .collect()
    }

    #[test]
    fn gapless_writes_full_chunks_straight_through() {
        // The stream that has already been burned against hardware: 27 sectors
        // at a time from LBA 0, filled across track boundaries, nothing
        // skipped. 1350 sectors is exactly fifty of them.
        let (issued, audio) = writes(&[300, 450, 600], true);
        let expected: Vec<(i32, u32)> = (0..50).map(|i| (i * 27, 27)).collect();
        assert_eq!(issued, expected);
        assert_eq!(audio.len(), 1350);
        assert_eq!(audio.iter().filter(|b| **b == 1).count(), 300);
        assert_eq!(&audio[..300], vec![1_u8; 300], "track 1 comes first, whole");
        assert_eq!(&audio[300..750], vec![2_u8; 450]);
        assert_eq!(&audio[750..], vec![3_u8; 600]);
    }

    #[test]
    fn a_gap_costs_150_addresses_and_not_one_byte() {
        let lengths = [300_u32, 450, 600];
        let (gapless, gapless_audio) = writes(&lengths, true);
        let (gapped, gapped_audio) = writes(&lengths, false);

        let transferred = |issued: &[(i32, u32)]| issued.iter().map(|(_, s)| *s).sum::<u32>();
        assert_eq!(transferred(&gapless), 1350);
        assert_eq!(transferred(&gapped), 1350, "the drive writes the pauses");
        assert_eq!(gapless_audio, gapped_audio, "the same audio, in the same order");

        // Each pause pushes the tracks after it 150 sectors further out, which
        // is where the cue sheet puts them: index 1 at 00:02:00 + 150 per gap.
        assert_eq!(track_starts(&gapless, &lengths), vec![0, 300, 750]);
        assert_eq!(track_starts(&gapped, &lengths), vec![0, 450, 1050]);
    }

    #[test]
    fn a_chunk_ending_exactly_on_a_track_boundary_still_takes_its_pause() {
        // 27 sectors fill the buffer at the very moment the file runs out, so
        // the pause has to survive into the next chunk rather than be lost.
        assert_eq!(writes(&[27, 27], false).0, vec![(0, 27), (177, 27)]);
        assert_eq!(writes(&[27, 27], true).0, vec![(0, 27), (27, 27)]);
    }

    #[test]
    fn a_single_track_is_written_the_same_way_either_way() {
        // There is nothing to sit between, so there is no pause to step over.
        assert_eq!(writes(&[300], false).0, writes(&[300], true).0);
    }

    // ── Write speed ──────────────────────────────────────────────────────

    #[test]
    fn one_times_speed_is_176_kilobytes_a_second() {
        // 75 sectors of 2352 bytes a second is 176.4 kB/s, and the field is a
        // whole number of them.
        assert_eq!(sectors_per_second_to_kbps(SECTORS_PER_SECOND), Some(176));
        // And it scales: 4x, 8x, 48x, the speeds a drive actually offers.
        assert_eq!(sectors_per_second_to_kbps(4 * SECTORS_PER_SECOND), Some(706));
        assert_eq!(sectors_per_second_to_kbps(8 * SECTORS_PER_SECOND), Some(1411));
        assert_eq!(sectors_per_second_to_kbps(48 * SECTORS_PER_SECOND), Some(8467));
    }

    #[test]
    fn a_speed_that_is_not_a_speed_is_refused_rather_than_wrapped() {
        // Zero would ask the drive to stop, so it is not a speed to send.
        assert_eq!(sectors_per_second_to_kbps(0), None);

        // 27 940 sectors/s is around 372x — nonsense for a CD, and exactly the
        // kind of nonsense that must not survive the 16-bit field: it comes to
        // 65 715 kB/s, which truncated would read back as 179 kB/s and burn the
        // disc at 1x. Refusing it leaves the drive to choose instead.
        assert_eq!(sectors_per_second_to_kbps(27_940), None);
        assert_eq!(sectors_per_second_to_kbps(u32::MAX), None);

        // FFFFh is the spec's "your maximum", not a speed, so the conversion
        // stops just short of it.
        assert_eq!(sectors_per_second_to_kbps(27_863), Some(65_534));
        assert_eq!(sectors_per_second_to_kbps(27_864), None);
    }

    #[test]
    fn set_cd_speed_puts_the_write_speed_in_the_write_field() {
        // 4x: 300 sectors/s, 706 kB/s, 02C2h.
        let kbps = sectors_per_second_to_kbps(4 * SECTORS_PER_SECOND).expect("a real speed");
        let cdb = set_cd_speed_cdb(kbps);

        assert_eq!(cdb.len(), 12, "SET CD SPEED is a 12-byte command");
        assert_eq!(cdb[0], 0xBB, "SET CD SPEED");
        assert_eq!(cdb[1] & 0x03, 0x00, "CLV/zone-CAV, not pure CAV");
        assert_eq!(&cdb[2..4], &[0xFF, 0xFF], "read speed: leave it at maximum");
        assert_eq!(&cdb[4..6], &[0x02, 0xC2], "write speed, big-endian");
        assert_eq!(&cdb[6..], &[0; 6], "the rest is reserved");
    }
}

