//! Session-At-Once writing on Linux, with an optional CD-TEXT lead-in.
//!
//! A direct translation of the Windows path in `win_sao.rs`. The three things
//! that had to be right against real drives are the same three on both, and
//! are worth restating because none of them is obvious:
//!
//! 1. The lead-in DATA FORM is `41h` — raw P-W from the host, main channel
//!    generated by the drive.
//! 2. The lead-in is **the whole lead-in**, from the disc's ATIP start (around
//!    97 minutes, so ~13 500 sectors) up to the pregap at −150, with the pack
//!    sequence repeated to fill it. Writing only enough sectors to hold the
//!    packs once produces a disc whose CD-TEXT cannot be read back.
//! 3. The cue sheet's lead-in entry carries the disc's real lead-in start,
//!    read from `READ DISC INFORMATION`, not zero.
//!
//! Unlike Windows there is no second path to fall back to, so a refusal during
//! setup is reported rather than quietly retried a different way. That makes
//! the ordering below matter: everything up to and including `SEND CUE SHEET`
//! leaves the disc untouched.

use std::fs::File;
use std::io::Read;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

use tauri::AppHandle;

use super::sg::ScsiDevice;
use crate::cdtext::{CdTextBlock, CdTextInput, CdTextTrack, SUBCHANNEL_BYTES_PER_SECTOR};
use crate::job::{emit_progress, PROGRESS_THROTTLE_MS};
use crate::mmc::cue::{build_cue_sheet, CueTrack, Msf, PREGAP_SECTORS};
use crate::mmc::mode::{self, WriteParameters};
use crate::mmc::scsi;
use crate::mmc::{
    lead_in_sectors, lead_in_start_lba, read_disc_information_cdb, send_cue_sheet_cdb, write_10_cdb,
};
use crate::model::{BurnOptions, BurnPhase, BYTES_PER_AUDIO_SECTOR};
use crate::render::RenderedTrack;

/// Sectors per `WRITE(10)`. 27 × 2352 is 63 504 bytes, just under 64 KB, which
/// every drive accepts. The Windows path asks the drive for its real transfer
/// limit and clamps that to this; this one never asks, so the figure has to be
/// one no drive turns down.
const CHUNK_SECTORS: usize = 27;

const TIMEOUT_SETUP: u32 = 30;
const TIMEOUT_WRITE: u32 = 300;

/// Retry budget for a write the drive is too busy to take: 1000 retries 40 ms
/// apart, so 40 seconds of sleeping — plus whatever the refused commands
/// themselves cost — before the burn is given up on. Windows allows the same
/// 40 seconds, its `MAX_RETRIES` being 1000 as well, but spends it over 1000
/// attempts to this loop's 1001: it sleeps after its final failure, while this
/// one tests the counter first. The budget has to be that long because a drive
/// with a full buffer can hold the host off for tens of seconds, and giving up
/// early aborts the burn and spoils the disc. It used to be 24 retries — 25
/// attempts, 0.96 seconds of waiting — which is not the same thing at all.
const WRITE_RETRIES: u32 = 1000;
const WRITE_BACKOFF: Duration = Duration::from_millis(40);

/// Where the lead-in starts and how long it is.
struct LeadIn {
    start: Msf,
    sectors: u32,
}

/// Build the CD-TEXT block for this disc, or `None` when it cannot be encoded.
///
/// Deliberately identical to `win::cd_text_block`: the disc title and performer
/// come from the options the user filled in, not from guessing at the first
/// track, so the same queue produces the same disc on either platform.
pub fn cd_text_block(options: &BurnOptions, tracks: &[RenderedTrack]) -> Option<CdTextBlock> {
    let input = CdTextInput {
        disc_title: options.disc_title.clone().unwrap_or_default(),
        disc_performer: options.disc_performer.clone().unwrap_or_default(),
        tracks: tracks
            .iter()
            .map(|track| CdTextTrack {
                title: track.title.clone(),
                performer: track.artist.clone(),
            })
            .collect(),
    };
    match CdTextBlock::encode(&input) {
        Ok(block) => Some(block),
        Err(error) => {
            crate::app_eprintln!("[burn] CD-TEXT not written: {error}");
            None
        }
    }
}

/// One `WRITE(10)`'s worth of the program area.
struct Chunk {
    /// Sectors to step the write address over before this chunk: the pause the
    /// drive generates between two tracks. Nothing is transferred for it, but
    /// it takes up the addresses in between.
    skip: u32,
    /// Audio bytes waiting in the buffer. Whole sectors, unless a rendered
    /// file was truncated — which `write_program_area` tests for before it
    /// writes.
    bytes: usize,
}

/// Feeds the program area 2352-byte sectors, track after track.
struct SectorSource {
    files: Vec<File>,
    current: usize,
    /// The pause before each track after the first — zero when the user asked
    /// for a gapless disc, which is what makes the tracks run together.
    gap_sectors: u32,
    /// A pause the next chunk must start after.
    pending_gap: u32,
}

impl SectorSource {
    fn open(tracks: &[RenderedTrack], gap_sectors: u32) -> Result<Self, String> {
        let files = tracks
            .iter()
            .map(|track| {
                File::open(&track.path)
                    .map_err(|e| format!("cannot read {}: {e}", track.path.display()))
            })
            .collect::<Result<Vec<_>, _>>()?;
        Ok(Self {
            files,
            current: 0,
            gap_sectors,
            pending_gap: 0,
        })
    }

    /// Fill `buffer` with whole sectors and say where they belong.
    ///
    /// A file that reads back nothing is the end of that track, not of the
    /// chunk: the next track carries straight on filling the same buffer, and
    /// it still lands on a sector boundary because rendering padded every
    /// track out to a whole one.
    ///
    /// A chunk never straddles a gap. A pause leaves 150 sectors between the
    /// tail of one track and the head of the next, and a `WRITE(10)` addresses
    /// one unbroken run, so the tail is written on its own and the pause is
    /// handed to the caller as `skip`. With no gap the tracks are contiguous
    /// and a chunk is filled from as many files as it takes, which is what
    /// keeps the drive fed.
    fn read(&mut self, buffer: &mut [u8]) -> Result<Chunk, String> {
        let mut skip = std::mem::take(&mut self.pending_gap);
        let mut filled = 0;
        while filled < buffer.len() && self.current < self.files.len() {
            let read = self.files[self.current]
                .read(&mut buffer[filled..])
                .map_err(|e| format!("reading rendered audio failed: {e}"))?;
            if read > 0 {
                filled += read;
                continue;
            }
            // This track's file is spent; the next one continues the disc.
            self.current += 1;
            if self.current < self.files.len() {
                self.pending_gap += self.gap_sectors;
            }
            if self.pending_gap == 0 {
                continue;
            }
            if filled == 0 {
                // Nothing is buffered yet, so this chunk can start after the
                // pause instead of leaving an empty one behind — a chunk of no
                // bytes is how the caller knows the disc is finished.
                skip += std::mem::take(&mut self.pending_gap);
                continue;
            }
            break;
        }
        Ok(Chunk { skip, bytes: filled })
    }
}

/// Write the whole session. Returns the program-area sectors written.
#[allow(clippy::too_many_arguments)] // One write; bundling would only move the arity.
pub fn write_session(
    app: &AppHandle,
    job_id: &str,
    device: &ScsiDevice,
    tracks: &[RenderedTrack],
    cd_text: Option<&CdTextBlock>,
    catalog: Option<&str>,
    gapless: bool,
    test_write: bool,
    buffer_underrun_free: bool,
    cancel: &Arc<AtomicBool>,
) -> Result<u32, String> {
    // ── Negotiation. Nothing below writes to the disc. ───────────────────
    configure_write_parameters(device, cd_text.is_some(), test_write, buffer_underrun_free)?;

    let cue_tracks: Vec<CueTrack> = tracks
        .iter()
        .map(|track| CueTrack {
            sectors: track.sectors,
            isrc: track.isrc.clone(),
        })
        .collect();

    // The lead-in geometry has to be known before the cue sheet, which
    // announces where the lead-in starts.
    let lead_in = match cd_text {
        Some(_) => Some(read_lead_in(device)?),
        None => None,
    };
    // Gapless rides in the cue sheet: this path has no second switch for it the
    // way IMAPI2 does on Windows, so a sheet built without it burned the same
    // disc whichever way the user set the toggle.
    let sheet = build_cue_sheet(
        &cue_tracks,
        lead_in.as_ref().map(|l| l.start),
        catalog,
        gapless,
    );
    device
        .send(&send_cue_sheet_cdb(sheet.len() as u32), &sheet, TIMEOUT_SETUP)
        .map_err(|e| format!("the drive would not accept the disc layout: {e}"))?;

    if cancel.load(Ordering::Relaxed) {
        return Err("cancelled".to_string());
    }

    // ── Past this line the laser is on. ──────────────────────────────────
    //
    // The audio, and only the audio: the drive generates the pauses, so this is
    // the length of the WRITE(10) stream whether or not the disc is gapped. The
    // disc itself is longer than this by 150 sectors per gap, which is the cue
    // sheet's business and not the transfer's.
    let sectors_total: u32 = tracks.iter().map(|track| track.sectors).sum();

    if let (Some(block), Some(lead_in)) = (cd_text, lead_in.as_ref()) {
        write_cd_text_lead_in(device, block, lead_in)?;
    }

    let written = write_program_area(app, job_id, device, tracks, sectors_total, gapless, cancel)?;

    device
        .execute(&scsi::synchronize_cache_cdb(), TIMEOUT_WRITE)
        .map_err(|e| format!("the drive could not flush its buffer: {e}"))?;

    Ok(written)
}

/// Read the Write Parameters page, edit it, and hand it back.
fn configure_write_parameters(
    device: &ScsiDevice,
    cd_text: bool,
    test_write: bool,
    buffer_underrun_free: bool,
) -> Result<(), String> {
    let mut buffer = [0_u8; 128];
    let cdb = scsi::mode_sense_10_cdb(scsi::PAGE_WRITE_PARAMETERS, buffer.len() as u16);
    let read = device
        .receive(&cdb, &mut buffer, TIMEOUT_SETUP)
        .map_err(|e| format!("the drive would not report its write settings: {e}"))?;

    let page = scsi::mode_page_from_sense(&buffer[..read])
        .ok_or_else(|| "the drive returned no write-parameters page".to_string())?;

    let edited = mode::apply(
        page,
        WriteParameters {
            test_write,
            buffer_underrun_free,
            raw_subchannel: cd_text,
        },
    )
    .map_err(|e| format!("the drive's write settings could not be prepared: {e}"))?;

    let payload = scsi::mode_select_payload(&edited);
    device
        .send(
            &scsi::mode_select_10_cdb(payload.len() as u16),
            &payload,
            TIMEOUT_SETUP,
        )
        .map_err(|e| format!("the drive refused Session-At-Once: {e}"))
}

/// Where this disc's lead-in begins, from `READ DISC INFORMATION` bytes 17..20.
fn read_lead_in(device: &ScsiDevice) -> Result<LeadIn, String> {
    let mut buffer = [0_u8; 34];
    let read = device
        .receive(
            &read_disc_information_cdb(buffer.len() as u16),
            &mut buffer,
            TIMEOUT_SETUP,
        )
        .map_err(|e| format!("the drive would not describe the disc: {e}"))?;

    if read < 20 {
        return Err("the drive returned no lead-in address for this disc".to_string());
    }

    let start = Msf {
        minute: buffer[17],
        second: buffer[18],
        frame: buffer[19],
    };
    let sectors = lead_in_sectors(start.to_sector());
    crate::app_deprintln!(
        "[burn] lead-in starts at {:02}:{:02}:{:02} ({} sectors)",
        start.minute,
        start.second,
        start.frame,
        sectors
    );
    Ok(LeadIn { start, sectors })
}

/// Write the CD-TEXT across the entire lead-in.
///
/// The pack sequence is repeated to fill it — a lead-in holding the packs only
/// once produces a disc whose CD-TEXT no player can find.
fn write_cd_text_lead_in(
    device: &ScsiDevice,
    block: &CdTextBlock,
    lead_in: &LeadIn,
) -> Result<(), String> {
    let subchannel = block.to_subchannel();
    let source_sectors = subchannel.len() / SUBCHANNEL_BYTES_PER_SECTOR;
    if source_sectors == 0 {
        return Ok(());
    }

    let mut lba = lead_in_start_lba(lead_in.sectors);
    let mut remaining = lead_in.sectors as usize;
    let mut cursor = 0_usize;

    while remaining > 0 {
        let batch = remaining.min(CHUNK_SECTORS);
        let mut payload = Vec::with_capacity(batch * SUBCHANNEL_BYTES_PER_SECTOR);
        for _ in 0..batch {
            let at = cursor * SUBCHANNEL_BYTES_PER_SECTOR;
            payload.extend_from_slice(&subchannel[at..at + SUBCHANNEL_BYTES_PER_SECTOR]);
            cursor = (cursor + 1) % source_sectors;
        }

        write_with_backoff(device, lba, batch as u16, &payload)
            .map_err(|reason| format!("writing the CD-TEXT lead-in failed: {reason}"))?;
        lba += batch as i32;
        remaining -= batch;
    }
    Ok(())
}

/// Send one `WRITE(10)`, waiting out a full drive buffer rather than failing.
///
/// A drive that cannot take more data reports Not Ready / "long write in
/// progress" (sense `2/04/08`). That is back-pressure, not an error — the only
/// correct response is to wait and try the same block again. Treating it as a
/// failure would abort a burn mid-disc for no reason, and writing a whole
/// lead-in makes hitting it near-certain.
///
/// Only that one triplet is back-pressure, so only it is retried. Matching any
/// ASCQ under 2/04 also caught conditions that never clear by themselves —
/// 2/04/03 is the drive waiting on the user — and burned the whole budget
/// sleeping before reporting them.
///
/// The reason comes back unwrapped because both call sites want to say which
/// part of the disc was being written when it happened.
///
/// Running the budget out says so in as many words, which is what Windows
/// already reported. A drive still asking for time has refused nothing, so
/// handing its "not ready" sense back made a drive that was merely slow read
/// exactly like one that turned the command down on sight.
fn write_with_backoff(
    device: &ScsiDevice,
    lba: i32,
    blocks: u16,
    payload: &[u8],
) -> Result<(), String> {
    let cdb = write_10_cdb(lba, blocks);
    let mut attempt = 0;
    loop {
        match device.send(&cdb, payload, TIMEOUT_WRITE) {
            Ok(()) => return Ok(()),
            Err(error) => {
                if !matches!(error.sense, Some((0x02, 0x04, 0x08))) {
                    return Err(error.to_string());
                }
                if attempt == WRITE_RETRIES {
                    return Err("the drive stayed busy for too long".to_string());
                }
                attempt += 1;
                std::thread::sleep(WRITE_BACKOFF);
            }
        }
    }
}

/// Write the audio, reporting progress as it goes.
fn write_program_area(
    app: &AppHandle,
    job_id: &str,
    device: &ScsiDevice,
    tracks: &[RenderedTrack],
    sectors_total: u32,
    gapless: bool,
    cancel: &Arc<AtomicBool>,
) -> Result<u32, String> {
    // The pause between two tracks is the drive's to write, exactly like the
    // pregap before track 1: it never reaches this buffer, only the address.
    let gap_sectors = if gapless { 0 } else { PREGAP_SECTORS };
    let mut source = SectorSource::open(tracks, gap_sectors)?;
    let mut buffer = vec![0_u8; CHUNK_SECTORS * BYTES_PER_AUDIO_SECTOR];
    let mut lba: i32 = 0;
    let mut written: u32 = 0;
    let mut last_emit = Instant::now();

    emit_progress(
        app,
        job_id,
        BurnPhase::Writing,
        None,
        0,
        sectors_total,
        None,
    );

    loop {
        if cancel.load(Ordering::Relaxed) {
            return Err("cancelled".to_string());
        }

        let chunk = source.read(&mut buffer)?;
        if chunk.bytes == 0 {
            break;
        }
        // Rendering pads every track to a sector boundary, so a partial sector
        // here means a truncated file. On a gapped disc it can arrive in the
        // middle of the queue as well as at the end, because a chunk stops at
        // a pause instead of running on into the next file. Writing the whole
        // sectors and dropping the tail would start every later track a sector
        // early and finish the session short of the lead-out the cue sheet has
        // already announced, with the drive still waiting for audio, so stop
        // instead.
        if !chunk.bytes.is_multiple_of(BYTES_PER_AUDIO_SECTOR) {
            return Err(
                "the rendered audio ended mid-sector; the burn cannot continue".to_string(),
            );
        }

        // Step over the pause before this track. The drive writes those sectors
        // from its own silence, so they are addresses to us and nothing else —
        // the same jump the lead-in write makes when it stops at −151 and
        // leaves the pregap to the drive.
        lba += chunk.skip as i32;

        let sectors = chunk.bytes / BYTES_PER_AUDIO_SECTOR;

        write_with_backoff(device, lba, sectors as u16, &buffer[..chunk.bytes])
            .map_err(|reason| format!("writing to the disc failed: {reason}"))?;

        lba += sectors as i32;
        written += sectors as u32;

        if last_emit.elapsed().as_millis() >= PROGRESS_THROTTLE_MS {
            last_emit = Instant::now();
            emit_progress(
                app,
                job_id,
                BurnPhase::Writing,
                None,
                written,
                sectors_total,
                None,
            );
        }
    }

    emit_progress(
        app,
        job_id,
        BurnPhase::Writing,
        None,
        written,
        sectors_total,
        None,
    );
    Ok(written)
}
